In [7]:
import pandas as pd

data = pd.read_csv("customers-100.csv") #random csv file from internet
print(data)
print(data.head(10))
print(data.tail(10))

    Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter
1       2  1Ef7b82A4CAAD10    Preston    Lozano
2       3  6F94879bDAfE5a6        Roy     Berry
3       4  5Cef8BFA16c5e3c      Linda     Olsen
4       5  053d585Ab6b3159     Joanna    Bender
..    ...              ...        ...       ...
95     96  cb8E23e48d22Eae       Karl     Greer
96     97  CeD220bdAaCfaDf       Lynn  Atkinson
97     98  28CDbC0dFe4b1Db       Fred    Guerra
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer
99    100  2354a0E336A91A1   Clarence    Haynes

                            Company               City  \
0                   Rasmussen Group       East Leonard
1                       Vega-Gentry  East Jimmychester
2                     Murillo-Perry      Isabelborough
3   Dominguez, Mcmillan and Donovan         Bensonview
4          Martin, Lang and Andrade     West Priscilla
..                              ...                ...
95                        Carey LLC       East Richard
96            Ware, Burns and Oneal       New Bradview
97                    Schmitt-Jones         Ortegaland
98               Fitzgerald-Harrell    Lake Elijahview
99               Le, Nash and Cross          Judymouth

                       Country                 Phone 1  \
0                        Chile            229.077.5154
1                     Djibouti              5153435776
2          Antigua and Barbuda         +1-539-402-0259
3           Dominican Republic  001-808-617-6467x12895
4   Slovakia (Slovak Republic)  001-234-203-0635x76146
..                         ...                     ...
95                      Guyana     (188)169-1674x58692
96                   Sri Lanka         +1-846-706-2218
97             Solomon Islands    +1-753-067-8419x7170
98                       Aruba           (530)311-9786
99                    Honduras           (753)813-6941

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24
1         686-620-1820x944                 vmata@colon.com        2021-04-23
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17
..                     ...                             ...               ...
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30
96            605.413.3198               vkemp@ferrell.com        2021-07-10
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11
99            783.639.1472          colleen91@faulkner.biz        2020-03-11

                              Website
0          http://www.stephenson.com/
1               http://www.hobbs.com/
2            http://www.lawrence.com/
3          http://www.good-lyons.com/
4         https://goodwin-ingram.com/
..                                ...
95            http://hayes-perez.com/
96         https://novak-allison.com/
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/

[100 rows x 12 columns]
   Index      Customer Id First Name  Last Name  \
0      1  DD37Cf93aecA6Dc     Sheryl     Baxter
1      2  1Ef7b82A4CAAD10    Preston     Lozano
2      3  6F94879bDAfE5a6        Roy      Berry
3      4  5Cef8BFA16c5e3c      Linda      Olsen
4      5  053d585Ab6b3159     Joanna     Bender
5      6  2d08FB17EE273F4      Aimee      Downs
6      7  EA4d384DfDbBf77     Darren       Peck
7      8  0e04AFde9f225dE      Brett     Mullen
8      9  C2dE4dEEc489ae0     Sheryl     Meyers
9     10  8C2811a503C7c5a   Michelle  Gallagher

                           Company               City  \
0                  Rasmussen Group       East Leonard
1                      Vega-Gentry  East Jimmychester
2                    Murillo-Perry      Isabelborough
3  Dominguez, Mcmillan and Donovan         Bensonview
4         Martin, Lang and Andrade     West Priscilla
5                     Steele Group      Chavezborough
6     Lester, Woodard and Mitchell           Lake Ana
7     Sanford, Davenport and Giles            Kimport
8                   Browning-Simon       Robersonstad
9                     Beck-Hendrix         Elaineberg

                      Country                 Phone 1                Phone 2  \
0                       Chile            229.077.5154       397.884.0519x718
1                    Djibouti              5153435776       686-620-1820x944
2         Antigua and Barbuda         +1-539-402-0259    (496)978-3969x58947
3          Dominican Republic  001-808-617-6467x12895        +1-813-324-8756
4  Slovakia (Slovak Republic)  001-234-203-0635x76146  001-199-446-3860x3486
5      Bosnia and Herzegovina     (283)437-3886x88321           999-728-1637
6            Pitcairn Islands      (496)452-6181x3291   +1-247-266-0963x4995
7                    Bulgaria    001-583-352-7197x297       001-333-145-0369
8                      Cyprus       854-138-4911x5772    +1-448-910-2276x729
9                 Timor-Leste        739.218.2516x459   001-054-401-0347x617

                         Email Subscription Date                      Website
0     zunigavanessa@smith.info        2020-08-24   http://www.stephenson.com/
1              vmata@colon.com        2021-04-23        http://www.hobbs.com/
2          beckycarr@hogan.com        2020-03-25     http://www.lawrence.com/
3  stanleyblackwell@benson.org        2020-06-02   http://www.good-lyons.com/
4      colinalvarado@miles.net        2021-04-17  https://goodwin-ingram.com/
5          louis27@gilbert.com        2020-02-25       http://www.berger.net/
6          tgates@cantrell.com        2021-08-24          https://www.le.com/
7              asnow@colon.com        2021-04-12  https://hammond-ramsey.com/
8      mariokhan@ryan-pope.org        2020-01-13     https://www.bullock.net/
9            mdyer@escobar.net        2021-11-08           https://arias.com/
    Index      Customer Id First Name Last Name                      Company  \
90     91  5ef6d3eefdD43bE       Nina    Chavez                Byrd-Campbell
91     92  98b3aeDcC3B9FF3      Shane     Foley                   Rocha-Hart
92     93  aAb6AFc7AfD0fF3     Collin     Ayers                Lamb-Peterson
93     94  54B5B5Fe9F1B6C5     Sherry     Young      Lee, Lucero and Johnson
94     95  BE91A0bdcA49Bbc    Darrell   Douglas  Newton, Petersen and Mathis
95     96  cb8E23e48d22Eae       Karl     Greer                    Carey LLC
96     97  CeD220bdAaCfaDf       Lynn  Atkinson        Ware, Burns and Oneal
97     98  28CDbC0dFe4b1Db       Fred    Guerra                Schmitt-Jones
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer           Fitzgerald-Harrell
99    100  2354a0E336A91A1   Clarence    Haynes           Le, Nash and Cross

                City          Country                Phone 1  \
90    Cassidychester           Bhutan           053-344-3205
91  South Dannymouth          Hungary        +1-822-569-0302
92      South Lonnie         Anguilla       404-645-5351x012
93      Frankchester  Solomon Islands           158-687-1764
94      Daisyborough             Mali  001-084-845-9524x1777
95      East Richard           Guyana    (188)169-1674x58692
96      New Bradview        Sri Lanka        +1-846-706-2218
97        Ortegaland  Solomon Islands   +1-753-067-8419x7170
98   Lake Elijahview            Aruba          (530)311-9786
99         Judymouth         Honduras          (753)813-6941

                   Phone 2                           Email Subscription Date  \
90     +1-330-920-5422x571            elliserica@frank.com        2020-03-26
91  001-626-114-5844x55073              nsteele@sparks.com        2021-07-06
92   001-257-582-8850x8516        dudleyemily@gonzales.biz        2021-06-29
93       (438)375-6207x003     alan79@gates-mclaughlin.com        2021-04-04
94        001-769-564-6303        grayjean@lowery-good.com        2022-02-17
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30
96            605.413.3198               vkemp@ferrell.com        2021-07-10
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11
99            783.639.1472          colleen91@faulkner.biz        2020-03-11

                              Website
90              https://www.pugh.com/
91       https://www.holt-sparks.com/
92               http://www.ruiz.com/
93                https://travis.net/
94                 https://banks.biz/
95            http://hayes-perez.com/
96         https://novak-allison.com/
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/

In [9]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB
None

In [10]:
data.describe()

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [13]:
print(data.isnull().sum())

Index                0
Customer Id          0
First Name           0
Last Name            0
Company              0
City                 0
Country              0
Phone 1              0
Phone 2              0
Email                0
Subscription Date    0
Website              0
dtype: int64